config/routes.rb
Rails.application.routes.draw do
  resources :works do
    resources :contributors
    resources :todo_lists do
      resources :tasks do
        resources :comments do
          resources :attachments
        end
        resources :attachments
      end
    end
  end

  devise_for :users
  resources :users
  root to: 'welcome#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :tasks, :has_many => :attachments 

  

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :todo_list
  belongs_to :user
  has_many :comments
  has_many :attachments, as: :attachable

  validate :not_past_date

  # Validate the the due date not in the past.
  def not_past_date
    if self.due_date < Date.today
      errors.add(:due_date, 'not in past')
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource
  
  # GET /tasks
  # GET /tasks.json
  def index
    if current_user.role?("admin")
      @tasks = Task.all.order("created_at").page(params[:page]).per(5)
    else
      @tasks = current_user.tasks.page(params[:page]).per(5)
    end
    @user = User.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @work = Work.find(params[:work_id])
    @todo_list = TodoList.find(params[:todo_list_id])
    @task = Task.find(params[:id])
    @user = User.all

    @attachable = Task.find(params[:id])
    @attachments = @attachable.attachments
  end

  # GET /tasks/new
  def new
    @work = Work.find(params[:work_id])
    @todo_list = TodoList.find(params[:todo_list_id])
    @user = User.all
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @user = User.find(@task.user_id)

    respond_to do |format|
      if @task.save
        format.html { redirect_to :back, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: :back }
        UserMailer.delay.notif_task(@user, @task)
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to :back, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: :back }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:user_id, :due_date, :name, :description, :status, :todo_list_id)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for [@work, @todo_list, Task.new] do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label "Assigned to" %><br>
    <%= f.select(:user_id, @user.map { |u| [u.username, u.id] }) %>
  </div>
  <div class="field">
    <%= f.hidden_field :status, :value => "0" %>
    <%= f.hidden_field :todo_list_id, :value => params[:todo_list_id] %>
  </div>
  <div class="actions">
    <%= f.submit 'Create Task', :class => 'button right' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Task Assigned To You</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>Due date</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.name, work_todo_list_task_path(task.todo_list.work_id, task.todo_list_id, task.id) %></td>
        <td><%= task.due_date %></td>
        <td><%= task.status ? "Unresolved" : "Done" %></td>
        <td><%= link_to 'Mark as Done', work_todo_list_task_path(task.todo_list.work_id, task.todo_list_id, task.id),{:method => :put, :status => true} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @tasks %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @task.name %>
</h2>

<p>
  <%= @task.description %><br>
</p>

<p>
  <strong>Project:</strong>
  <%= link_to @work.title, work_path(@work.id), :class => "label" %>
  <strong>Filled under to list:</strong>
  <%= link_to @todo_list.name, work_todo_list_path(@work.id, @todo_list.id), :class => "label" %>
  <strong>Assigned to:</strong>
  <%= link_to @task.user.username, user_path(@task.user.id), :class => "label" %>
  <strong>Due date:</strong>
  <span class="label" ><%= @task.due_date %></span>
</p>

<h2>Attachment</h2>
<% @attachments.each do |a| %>
  <p>
    <%= image_tag a.attachment %>
  </p>
<% end %>


<h2>Discussion</h2>
<% @task.comments.each do |comment| %>
  <p>
    <strong><%= comment.user.username %>:</strong>
    <%= comment.body %>
  </p>
<% end %>

<%= form_for [@work, @todo_list, @task, @task.comments.build] do |f| %>
  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %> 
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'button right' %> 
  </div>
<% end %>