config/routes.rb
Rails.application.routes.draw do
  resources :works do
    resources :contributors
    resources :todo_lists do
      resources :tasks do
        resources :comments do
          resources :attachments
        end
        resources :attachments
      end
    end
  end

  devise_for :users
  resources :users
  root to: 'welcome#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :tasks, :has_many => :attachments 

  

end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  belongs_to :work
  has_many :tasks
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource
  
  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.where(work_id: params[:id]).order("created_at").page(params[:page]).per(5)
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
    @task = Task.where(todo_list_id: params[:id]).order('status DESC').order('due_date').page(params[:page]).per(5)
    @task.each do |t| 
      diff = (t.due_date - Date.today).to_i
      t.due_date = convert_due_date(diff)
     end
  end

  def convert_due_date(num)
    if num < 0
      return 0
    elsif num == 0
      return 1
    else 
      num = num
    end
    return num
  end

  # GET /todo_lists/new
  def new
  end

  # GET /todo_lists/1/edit
  def edit
    @todo_list = TodoList.find(params[:id])
    @work = Work.find(params[:work_id])
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to :back, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: :back }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to  work_todo_list_path, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: work_todo_list_path }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:name, :description, :work_id)
    end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/todo_lists/_form.html.erb
<%= form_for [@work, @todo_list] do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
  <%= f.submit :class => 'button right' %>  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo Lists</h1>

<%= render 'form' %>

app/views/todo_lists/index.html.erb
<h1>My ToDo List</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="2">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= link_to todo_list.name, todo_list %></td>
        <td><%= todo_list.description %></td>
        <% if can? :update, todo_list %>
        <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
        <% end %>
        <% if can? :destroy, todo_list %>
        <td><%= link_to 'Delete', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate @todo_lists %>

app/views/todo_lists/new.html.erb
<h1>Add New Todo List</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @todo_list.name %>
</h2>

<p>
  <%= @todo_list.description %>
</p>

<%= link_to 'Edit Todo List',  edit_work_todo_list_path(params[:work_id], @todo_list), :class => "button" %>

<h3>Related Task:</h3>
<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>Assign to</th>
      <th>Due Date</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @task.each do |task| %>
      <tr>
        <td><%= link_to task.name, work_todo_list_task_path(params[:work_id], params[:id], task.id) %></td>
        <td><%= link_to task.user.username, user_path(task.user_id) %></td>
        <td><%= task.due_date.to_s + ' days left' %></td>
        <td><%= task.status ? "On Progress" : "Completed" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @task %>

<%= link_to 'New Task', new_work_todo_list_task_path(params[:work_id], params[:id]), :class => "button" %>