config/routes.rb
Rails.application.routes.draw do
  resources :works do
    resources :contributors
    resources :todo_lists do
      resources :tasks do
        resources :comments do
          resources :attachments
        end
        resources :attachments
      end
    end
  end

  devise_for :users
  resources :users
  root to: 'welcome#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :tasks, :has_many => :attachments 

  

end

app/models/work.rb
class Work < ActiveRecord::Base
  belongs_to :user
  has_many :contributed_users, through: :contributor
  has_many :contributors
  has_many :todo_lists

  validates :title, presence: true
  attr_accessor :login
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /works
  # GET /works.json
  def index
    if current_user.role?("admin")
      @works = Work.all.order("created_at").page(params[:page]).per(5)
    else
      @works = current_user.works.page(params[:page]).per(5)
    end
    @user = User.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
    @contributor = Contributor.where(work_id: params[:id]).order('created_at')
    @todo_list = TodoList.where(work_id: params[:id]).order('created_at')
    
    # Select the user who not already assigned as contributor
    @u = User.all.where.not(id: current_user.id)
    @ids = @contributor.map{|x| x.user_id}
    @user = @u.reject{|x| @ids.include? x.id}
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:title, :description, :user_id )
    end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_form.html.erb
<%= form_for(@work) do |f| %>
  <% if @work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% @work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'button right' %> 
  </div>
<% end %>

app/views/works/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form' %>

app/views/works/index.html.erb
<h1>Manage Project</h1>

<table>
  <thead>
    <tr>
      <th width="200">Project</th>
      <th width="150">Action</th>
    </tr>
  </thead>
    <tbody>
        <% @works.each do |work| %>
          <tr>
            <td><%= link_to work.title, work %></td>
            <td>              
              <ul class="stack-for-small secondary button-group">
                <li>
                  <% if can? :update, work %>
                    <%= link_to 'Edit', edit_work_path(work), :class => "tiny button" %>
                  <% end %>
                </li>
                <li>
                <% if can? :destroy, work %>
                  <%= link_to 'Delete', work, method: :delete, data: { confirm: 'Are you sure?' }, :class => "tiny button [secondary alert success]" %>
                <% end %>              
                </li>
            </ul>
            </td>
          </tr>
        <% end %>
      </tbody>
</table>

<%= paginate @works %>

app/views/works/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @work.title %>
</h2>

<p>
  <strong>Project Owner:</strong>
  <%= @work.user.name %>
</p>

<p>
  <%= @work.description %>
</p>

<%= link_to 'Edit Project', edit_work_path(@work), :class => "button" %>

<p>
<strong>Project Contributor:</strong>
  <% @contributor.each do |contributor| %>
    <%= link_to contributor.user.name, user_path(contributor.user_id) %>
    <%= link_to 'X', work_contributor_path(contributor.work_id, contributor.id), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</p>

<%= form_for [@work, Contributor.new] do |f| %>
  <div class="field col6">
    <%= f.select(:user_id, @user.map { |u| [u.username, u.id] }) %>
  </div>
  <div class="field">
    <%= f.hidden_field :work_id, value: params[:id] %> 
  </div>
  <div class="actions">
    <%= f.submit "Add Contributor", :class => "button" %>
  </div>
<% end %>

<h3>Todo:</h3>
<table>
  <thead>
      <th>Todo</th>
      <th>Task On Progress</th>
      <th>Task Completed</th>
    </tr>
  </thead>

  <tbody>
    <% @todo_list.each do |todo| %>
      <tr>
        <td><%= link_to todo.name, work_todo_list_path(todo.work.id, todo.id) %></td>
        <td><%= todo.tasks.where(:status => false).count %></td>
        <td><%= todo.tasks.where(:status => true).count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= form_for [@work, TodoList.new] do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.hidden_field :work_id, value: params[:id] %> 
  </div>
  <div class="actions">
    <%= f.submit "Add Todo", :class => "button" %>
  </div>
<% end %>