config/routes.rb
Rails.application.routes.draw do
  resources :works do
    resources :contributors
    resources :todo_lists do
      resources :tasks do
        resources :comments do
          resources :attachments
        end
        resources :attachments
      end
    end
  end

  devise_for :users
  resources :users
  root to: 'welcome#index'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :tasks, :has_many => :attachments 

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Project Management Software</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><a href="#">Project Management Software</a></h1>
      </li>
       <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

      <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <% if user_signed_in? %>
          <li class="has-dropdown">       
            <%= link_to current_user.username, edit_user_registration_path %>
            <ul class="dropdown">
              <li><%= link_to "Edit profile", edit_user_registration_path %></li>
              <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="has-form"><%= link_to "Sign in", new_user_session_path, :class => "button" %><li>
        <% end %>
      </ul>

      <!-- Left Nav Section -->
      <% if user_signed_in? %>
      <ul class="left">
        <li class="has-dropdown">
          <%= link_to "My Project", works_path %>
          <ul class="dropdown">
            <li><a href="#">My Contribution</a></li>
            <li><%= link_to "My Task", work_todo_list_tasks_path(1,1) %></li>
          </ul>
        </li>
      </ul>
      <ul>
        <li class="has-form">
          <%= link_to 'New Project', new_work_path, :class => "button" %>
        </li>
      </ul>
      <% end %>
    </section>
  </nav>
  <div class="row">
    <div class="small-11 small-centered columns">
    <%= yield %>
    </div>
  </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>